version: '3.5'

services:
  blog:
    build:
      context: .
      dockerfile: Dockerfile
    image: django-blog
    container_name: django-blog
    ports:
      - "8000:8000"
    volumes:
      - .:${PWD}